name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable]
        mode: ["", "--release"]
        include:
          - os: ubuntu-latest
            toolchain: nightly
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      
      # https://github.com/actions/virtual-environments/issues/895
      # https://github.com/actions/virtual-environments/issues/936
      - if: ${{ runner.os == 'Windows' }}
        name: Clean up cargo registry files
        run: rm -r -fo $env:UserProfile\.cargo\registry

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets ${{ matrix.mode }} ${{ matrix.features }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.mode }} ${{ matrix.features }}

      
