name: Security audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.AUDIT_TOKEN }}